# Use an official Eclipse Temurin base image for Java 17
FROM eclipse-temurin:17

# Maintainer or author
LABEL maintainer="pereravasitha1@gmail.com"

# Set the working directory inside the container
WORKDIR /app

# Copy the exact JAR file generated by your pom.xml into the container
COPY target/sms-backend-0.0.1.jar /app/sms-backend.jar

# Define the ENTRYPOINT to run the jar file when the container starts
ENTRYPOINT ["java", "-jar", "/app/sms-backend.jar"]